/* NULL SHIFT — original browser game. Renderer: Three.js (MIT). No network required. */
(() => {
'use strict';
const $ = id => document.getElementById(id);
const clamp = (v,a,b) => Math.max(a,Math.min(b,v));
const TAU = Math.PI*2;
let seed=7102026;
function rand(){ seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296; }
const range=(a,b)=>a+rand()*(b-a);
const clockText=s=>`${Math.floor(s/60).toString().padStart(2,'0')}:${Math.floor(s%60).toString().padStart(2,'0')}`;
const safeStorage={get(k){try{return localStorage.getItem(k)}catch{return null}},set(k,v){try{localStorage.setItem(k,v)}catch{}}};
let quality=safeStorage.get('nullshift-quality')||'high',soundOn=safeStorage.get('nullshift-sound')!=='off';
let state='menu',difficulty='normal',elapsed=0,kills=0,score=0,health=100,focus=100,ammo=24,relaysDone=0;
let yaw=0,pitch=0,vy=0,jumps=0,shotTimer=0,reloadTimer=0,dashTimer=0,dashLeft=0,spawnTimer=0;
let slow=false,slowLatched=false,shooting=false,dragLook=false,damageFlash=0,hitFlash=0,killFlash=0,toastTimer=0,invincible=0;
let timeScale=1,realTime=0,stepCount=0,lastTime=performance.now(),hudClock=0,visualQuality=quality;
const keys=new Set(),enemies=[],bullets=[],particles=[],pickups=[],colliders=[],coverMeshes=[],relays=[],markers=[];
const touch={x:0,y:0,slow:false,hack:false}, isTouch=matchMedia('(pointer: coarse)').matches;
let scene,camera,renderer,gun,floor,rain,skyline,exitGroup,exitRing,screenScene,screenCamera,postMaterial,renderTarget,reflectionTarget,mirrorCamera,mirrorMatrix;
let detailedPhone,roofWorld,stationWorld,worldRoot,hemi;
let currentLevel=1,levelTwoUnlocked=safeStorage.get('nullshift-level2')==='unlocked',campaignComplete=safeStorage.get('nullshift-campaign')==='complete';
let stationMission={phase:'breakers',wait:35,progress:0};
const stationObjective=()=>({breakers:['Destroy both power cells','Shoot the glowing cells A and B to lower the archive shield.'],core:['Recover the data core','Shield down. Reach ARCHIVE and hold E to take the core.'],call:['Call your escape train','Carry the core to PLATFORM 01. Hold E at CALL.'],defend:['Hold the platform',`Survive ${Math.ceil(stationMission.wait)}s. Use the columns and bullet time.`],board:['Board the train','Train ready. Reach BOARD and hold E to escape.'],complete:['The signal is free','Archive delivered. Both missions complete.']}[stationMission.phase]);
let flashLight,weaponFlash,gunKick=0,gunBob=0,gunMuzzle,player,exitPos,raycaster,frustumDirection,shadowLight;
const v3=(x=0,y=0,z=0)=>new THREE.Vector3(x,y,z);
const mat=(color,roughness=.65,metalness=.1,extra={})=>new THREE.MeshStandardMaterial({color,roughness,metalness,...extra});
const greenMaterial=()=>new THREE.MeshBasicMaterial({color:0xc4ff9d});
const enemyMat={};
const shared={};
function box(w,h,d,material,x=0,y=0,z=0,parent=scene){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),material);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
function cylinder(r1,r2,h,material,x,y,z,parent=scene,n=12){const m=new THREE.Mesh(new THREE.CylinderGeometry(r1,r2,h,n),material);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
function addCollider(x,z,w,d,height){colliders.push({x,z,w:w/2,d:d/2,height});}
function circleBlocked(x,z,r,height=0){if(Math.abs(x)>31-r||Math.abs(z)>39-r)return true;return colliders.some(b=>height<b.height&&x+r>b.x-b.w&&x-r<b.x+b.w&&z+r>b.z-b.d&&z-r<b.z+b.d);}
function moveBody(body,dx,dz,r=.4,height=0){const steps=Math.max(1,Math.ceil(Math.max(Math.abs(dx),Math.abs(dz))/.18));for(let i=0;i<steps;i++){if(!circleBlocked(body.x+dx/steps,body.z,r,height))body.x+=dx/steps;if(!circleBlocked(body.x,body.z+dz/steps,r,height))body.z+=dz/steps;}}
function intersectBox(origin,dir,b,maxDistance){let lo=0,hi=maxDistance;for(const [p,d,min,max] of [[origin.x,dir.x,b.x-b.w,b.x+b.w],[origin.y,dir.y,b.bottom||0,b.height],[origin.z,dir.z,b.z-b.d,b.z+b.d]]){if(Math.abs(d)<1e-7){if(p<min||p>max)return false;}else{let a=(min-p)/d,c=(max-p)/d;if(a>c)[a,c]=[c,a];lo=Math.max(lo,a);hi=Math.min(hi,c);if(lo>hi)return false;}}return lo;}
function obstacleDistance(origin,dir,maxDistance){let nearest=maxDistance;for(const b of colliders){const t=intersectBox(origin,dir,b,nearest);if(t!==false)nearest=t;}return nearest;}

// Procedural surface textures are part of the real-time game, with a seeded world.
function surfaceTexture(type){const c=document.createElement('canvas');c.width=c.height=512;const ctx=c.getContext('2d');ctx.fillStyle=type==='ground'?'#354039':'#4a514a';ctx.fillRect(0,0,512,512);const data=ctx.getImageData(0,0,512,512);for(let i=0;i<data.data.length;i+=4){const n=(rand()-.5)*35;data.data[i]=clamp(data.data[i]+n,0,255);data.data[i+1]=clamp(data.data[i+1]+n,0,255);data.data[i+2]=clamp(data.data[i+2]+n,0,255);}ctx.putImageData(data,0,0);ctx.strokeStyle='#15221da0';ctx.lineWidth=3;for(let i=0;i<512;i+=128){ctx.beginPath();ctx.moveTo(i,0);ctx.lineTo(i,512);ctx.stroke();ctx.beginPath();ctx.moveTo(0,i);ctx.lineTo(512,i);ctx.stroke();}for(let i=0;i<40;i++){ctx.fillStyle=`rgba(2,10,6,${range(.01,.12)})`;ctx.beginPath();ctx.ellipse(rand()*512,rand()*512,range(10,80),range(3,25),rand()*3,0,TAU);ctx.fill();}const t=new THREE.CanvasTexture(c);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(type==='ground'?14:2,type==='ground'?18:2);t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=4;return t;}
function windowTexture(){const c=document.createElement('canvas');c.width=256;c.height=512;const ctx=c.getContext('2d');ctx.fillStyle='#0b1511';ctx.fillRect(0,0,256,512);for(let y=4;y<512;y+=16)for(let x=3;x<256;x+=16){const lit=rand();ctx.fillStyle=lit>.74?['#bdc5a0','#6f927c','#b0b998','#90b0a0'][Math.floor(rand()*4)]:lit>.4?'#1b2d27':'#0d1f19';ctx.fillRect(x,y,10,10);if(lit>.74){ctx.fillStyle='#17241c80';ctx.fillRect(x+4,y,1,10);}}const t=new THREE.CanvasTexture(c);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.colorSpace=THREE.SRGBColorSpace;return t;}
function labelTexture(text,color='#c4ff9a',sub=''){const c=document.createElement('canvas');c.width=512;c.height=256;const ctx=c.getContext('2d');ctx.fillStyle='#04120c';ctx.fillRect(0,0,512,256);ctx.strokeStyle='#7bd480';ctx.lineWidth=2;ctx.strokeRect(12,12,488,232);ctx.fillStyle=color;ctx.font='bold 62px Consolas, monospace';ctx.textAlign='center';ctx.fillText(text,256,123);ctx.font='20px Consolas, monospace';ctx.fillText(sub,256,182);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t;}
function makeEnvironment(){const images=[];for(let f=0;f<6;f++){const c=document.createElement('canvas');c.width=c.height=128;const ctx=c.getContext('2d');const g=ctx.createLinearGradient(0,0,0,128);g.addColorStop(0,'#1b3630');g.addColorStop(.5,'#345a4b');g.addColorStop(1,'#08160f');ctx.fillStyle=g;ctx.fillRect(0,0,128,128);for(let i=0;i<12;i++){ctx.fillStyle=i%4===0?'#b9d9b2':'#52826a';ctx.fillRect(rand()*128,rand()*128,3,range(2,20));}images.push(c);}const cube=new THREE.CubeTexture(images);cube.needsUpdate=true;cube.colorSpace=THREE.SRGBColorSpace;scene.environment=cube;}
function makeWorld(){
const concrete=mat(0x647469,.86,.13,{map:surfaceTexture('wall')}),metal=mat(0x78837c,.37,.78),darkMetal=mat(0x25372d,.4,.7),roofEdge=mat(0x435149,.8,.2);
const groundTexture=surfaceTexture('ground');
mirrorMatrix=new THREE.Matrix4();reflectionTarget=new THREE.WebGLRenderTarget(640,360,{minFilter:THREE.LinearFilter,magFilter:THREE.LinearFilter});mirrorCamera=new THREE.PerspectiveCamera();
const floorMat=window.NULLVISUALS?window.NULLVISUALS.floorMaterial():mat(0x9baa9e,.28,.38,{map:groundTexture,envMapIntensity:.7});
floorMat.onBeforeCompile=shader=>{shader.uniforms.mirrorMap={value:reflectionTarget.texture};shader.uniforms.mirrorMatrix={value:mirrorMatrix};shader.vertexShader='uniform mat4 mirrorMatrix; varying vec4 mirrorUV;\n'+shader.vertexShader;shader.vertexShader=shader.vertexShader.replace('#include <project_vertex>','#include <project_vertex>\nmirrorUV = mirrorMatrix * modelMatrix * vec4(transformed,1.);');shader.fragmentShader='uniform sampler2D mirrorMap; varying vec4 mirrorUV;\n'+shader.fragmentShader;shader.fragmentShader=shader.fragmentShader.replace('#include <dithering_fragment>','vec2 reflectionUV=mirrorUV.xy/mirrorUV.w; vec3 wet=texture2D(mirrorMap,reflectionUV).rgb; float puddle=smoothstep(.24,.62,texture2D(map,vMapUv*.31).r); gl_FragColor.rgb=mix(gl_FragColor.rgb,wet,0.16+puddle*.32);\n#include <dithering_fragment>');};
floor=new THREE.Mesh(new THREE.PlaneGeometry(64,80),floorMat);floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;scene.add(floor);
box(64,20,80,concrete,0,-10.03,0); // skyscraper below the playable roof
for(const x of [-31.7,31.7])box(.5,.65,80,roofEdge,x,.28,0);
for(const z of [-39.7,39.7])box(64,.65,.5,roofEdge,0,.28,z);
const neon=new THREE.MeshBasicMaterial({color:0x9ce877});
for(const x of [-31.36,31.36])box(.055,.045,78,neon,x,.63,0);
for(const z of [-39.36,39.36])box(63,.045,.055,neon,0,.63,z);
// Rooftop ventilation stacks and cover lanes.
for(const [x,z,w,d,h] of [[-10,10,6,4,2.2],[11,5,5,7,2.2],[-12,-10,5,6,2.3],[13,-15,6,4,2.1],[0,-5,6,3,1.1],[-23,14,3,7,1.8],[23,21,5,4,1.5],[0,-27,7,3,1.5]]){
const m=box(w,h,d,metal,x,h/2,z);coverMeshes.push(m);addCollider(x,z,w,d,h);
box(w+.16,.12,d+.16,darkMetal,x,h+.06,z);
for(let k=0;k<8;k++)box(w-.3,.055,.09,darkMetal,x,.3+k*(h-.45)/8,z+d/2+.01);
const fan=cylinder(Math.min(w,d)*.28,Math.min(w,d)*.28,.08,darkMetal,x,h+.16,z);for(let k=0;k<4;k++){const b=box(Math.min(w,d)*.4,.035,.17,metal,x,h+.22,z);b.rotation.y=k*Math.PI/4;}
}
for(const [x,z] of [[-26,-3],[25,-3],[-7,-33],[7,31]]){box(2.2,1.2,2.2,darkMetal,x,.6,z);addCollider(x,z,2.2,2.2,1.2);for(const a of [-.8,.8])box(.065,1.25,2.3,metal,x+a,.62,z);}
// Overhead pipework and warm security lamps.
for(const x of [-28,28]){cylinder(.14,.14,8,metal,x,4,-7);const beam=box(.22,.22,11,metal,x,7.8,-2);box(.5,.12,1.3,new THREE.MeshBasicMaterial({color:0xffe3a2}),x,7.55,2);const lamp=new THREE.PointLight(0xd0e5bc,35,19,2);lamp.position.set(x,6.8,2);scene.add(lamp);}
for(const z of [-29,29]){const pipe=cylinder(.2,.2,42,metal,0,.4,z);pipe.rotation.z=Math.PI/2;}
// Architectural skyline with varied heights, lit floors and rooftop towers.
skyline=window.NULLVISUALS.city(scene);
const moon=new THREE.Mesh(new THREE.SphereGeometry(8,24,16),new THREE.MeshBasicMaterial({color:0xabcabd,fog:false}));moon.position.set(-100,150,-250);scene.add(moon);
// Terminal relays: visible screens, physical cover, objective beacons.
for(const [i,x,z] of [[0,-23,-23],[1,23,-25],[2,1,-35]]){
const group=new THREE.Group();group.position.set(x,0,z);scene.add(group);
box(1.7,1.65,.9,darkMetal,0,.83,0,group);box(1.35,.85,.06,new THREE.MeshBasicMaterial({map:labelTexture(`0${i+1}`,'#c4ff9a','HOLD [E] TO BREACH')}),0,1.22,.48,group);box(1.6,.07,.5,metal,0,.72,.64,group);addCollider(x,z,1.7,.9,1.65);
const ring=new THREE.Mesh(new THREE.TorusGeometry(2,.035,5,60),greenMaterial());ring.rotation.x=Math.PI/2;ring.position.y=.08;group.add(ring);
const beam=new THREE.Mesh(new THREE.CylinderGeometry(.35,.35,11,12,1,true),new THREE.MeshBasicMaterial({color:0xaaff88,transparent:true,opacity:.09,depthWrite:false,side:THREE.DoubleSide}));beam.position.y=5.5;group.add(beam);
const light=new THREE.PointLight(0xa0ff74,12,8,2);light.position.set(0,1.8,1);group.add(light);
const marker=document.createElement('div');marker.className='marker';$('markers').append(marker);relays.push({group,x,z,progress:0,done:false,ring,beam,light,marker});
}
exitPos=v3(0,0,32);exitGroup=new THREE.Group();exitGroup.position.copy(exitPos);scene.add(exitGroup);
box(2.3,.2,2.3,darkMetal,0,.1,0,exitGroup);for(const x of [-1.05,1.05])box(.15,3,.15,metal,x,1.5,0,exitGroup);box(2.3,.2,.18,metal,0,3,0,exitGroup);
exitRing=new THREE.Mesh(new THREE.PlaneGeometry(1.9,2.8),new THREE.MeshBasicMaterial({color:0xb7ffe7,transparent:true,opacity:.0,side:THREE.DoubleSide,depthWrite:false}));exitRing.position.set(0,1.5,0);exitGroup.add(exitRing);
box(1.8,.48,.1,new THREE.MeshBasicMaterial({map:labelTexture('EXIT','#c5fbe2','OFFLINE')}),0,3.45,0,exitGroup);
const exitMarker=document.createElement('div');exitMarker.className='marker exit';$('markers').append(exitMarker);markers.push({element:exitMarker,position:v3(0,4.2,32)});
// Rain is a single batched geometry, so weather remains light enough for Chrome.
const rainCount=1300;const positions=new Float32Array(rainCount*6);for(let i=0;i<rainCount;i++){const x=range(-48,48),y=range(0,36),z=range(-50,50);positions.set([x,y,z,x-.1,y-.8,z],i*6);}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(positions,3));rain=new THREE.LineSegments(g,new THREE.LineBasicMaterial({color:0x8ab8a6,transparent:true,opacity:.22,depthWrite:false}));rain.frustumCulled=false;scene.add(rain);detailedPhone=window.NULLVISUALS.rooftop(scene,colliders,exitGroup);
}

function buildWorlds(){const before=new Set(scene.children);makeWorld();const root=new THREE.Group();root.name='RooftopMission';for(const object of [...scene.children])if(!before.has(object))root.add(object);scene.add(root);roofWorld={root,floor,colliders:[...colliders],relays:[...relays],markers:[...markers],exitPos,exitRing,exitGroup,detailedPhone};worldRoot=root;}
function switchWorld(level){currentLevel=level;if(!roofWorld)return;if(level===2&&!stationWorld){stationWorld=window.NULLSTATION.build(roofWorld.floor.material);scene.add(stationWorld.root);stationWorld.markers=[];for(const item of [...stationWorld.breakers.map(b=>({label:b.id,position:v3(b.x,4.7,b.z),kind:'cell',cell:b})),{label:'ARCHIVE',position:v3(-4,4,-31),kind:'core'},{label:'CALL',position:v3(15,3.8,18),kind:'call'},{label:'BOARD',position:v3(17.4,3,20),kind:'board'}]){const element=document.createElement('div');element.className='marker';element.hidden=true;$('markers').append(element);stationWorld.markers.push({...item,element});}}
roofWorld.root.visible=level===1;rain.visible=level===1;if(stationWorld)stationWorld.root.visible=level===2;for(const r of roofWorld.relays)r.marker.hidden=true;for(const m of [...roofWorld.markers,...(stationWorld?.markers||[])])m.element.hidden=true;
const world=level===1?roofWorld:stationWorld;worldRoot=world.root;floor=world.floor;colliders.splice(0,colliders.length,...world.colliders);relays.splice(0,relays.length,...(world.relays||[]));markers.splice(0,markers.length,...(world.markers||[]));exitPos=world.exitPos;exitRing=level===1?roofWorld.exitRing:null;detailedPhone=level===1?roofWorld.detailedPhone:null;
scene.background.setHex(level===1?0x18302b:0x0c1913);scene.fog.color.setHex(level===1?0x203c32:0x172a21);scene.fog.density=level===1?.0065:.011;hemi.intensity=level===1?2.4:1.65;shadowLight.intensity=level===1?2.2:.72;shadowLight.castShadow=level===1;document.body.dataset.level=String(level);$('world').setAttribute('aria-label',level===1?'3D rooftop arena':'3D underground station');}
function updateCampaignMenu(){const option=$('mission-select').querySelector('option[value="2"]');option.disabled=!levelTwoUnlocked;option.textContent=levelTwoUnlocked?'02 / LAST TRAIN':'02 / LAST TRAIN — LOCKED';$('unlock-note').textContent=levelTwoUnlocked?(campaignComplete?'Both missions complete. Choose a mission to replay.':'Last Train unlocked. Continue your escape underground.'):'Complete The Rooftops to unlock Last Train.';}
function selectMission(){const level=Number($('mission-select').value);if(level===2&&!levelTwoUnlocked)return;switchWorld(level);$('mission-number').textContent=level===1?'01':'02';$('mission-caption').textContent=level===1?'THE ROOFTOPS':'LAST TRAIN';$('mission-meta').textContent=level===1?'03:14 AM / RAIN / SYSTEM ACTIVE':'03:21 AM / MARA CENTRAL / SERVICE SUSPENDED';$('mission-brief').innerHTML=level===1?'Three relays. A rooftop full of agents.<br>One way out.':'Steal the core. Hold the platform.<br>Catch the last train out.';updateRecord();}
function nextLevel(){if(state==='won'&&currentLevel===1&&levelTwoUnlocked){$('end').hidden=true;$('briefing').hidden=false;}}
function damagePowerCell(cell){if(currentLevel!==2||stationMission.phase!=='breakers'||cell.done)return;cell.hp=Math.max(0,cell.hp-40);burst(cell.orb.getWorldPosition(v3()),0xb8ff89,10);hitFlash=.15;tone(350,.13,.09,'square',80);if(cell.hp===0){cell.done=true;cell.orb.visible=cell.beam.visible=cell.ring.visible=false;score+=400;focus=100;const count=stationWorld.breakers.filter(b=>b.done).length;toast(count===2?'SHIELD DOWN. Recover the archive core.':`POWER CELL ${cell.id} OFFLINE. One cell remains.`,4);if(count===2){stationMission.phase='core';stationMission.progress=0;stationWorld.shield.visible=false;tone(440,.6,.13,'sine',880);}spawnEnemy();}}
function updateStationMission(dt){if(state!=='playing')return;const m=stationMission;const phase=m.phase;
if(phase==='defend'){const old=m.wait;m.wait=Math.max(0,m.wait-dt);for(const threshold of [24,12])if(old>threshold&&m.wait<=threshold){spawnEnemy();spawnEnemy();tone(110,.4,.08,'sawtooth',55);toast('AGENT REINFORCEMENTS. Keep the core alive.',3);}if(m.wait===0){m.phase='board';m.progress=0;m.requireRelease=true;health=clamp(health+20,0,100);score+=500;tone(740,.7,.15,'sine',370);toast('TRAIN ARRIVED. Hold E at the green BOARD beacon.',5);}}
let target=null,label='',duration=1.5;if(m.phase==='core'){target=v3(-4,0,-31);label='RECOVER DATA CORE';duration=1.6;}else if(m.phase==='call'){target=v3(15,0,18);label='INSERT CORE / CALL TRAIN';duration=1.8;}else if(m.phase==='board'){target=exitPos;label='BOARD THE TRAIN';duration=1;}
const held=keys.has('KeyE')||touch.hack;if(!held)m.requireRelease=false;const near=target&&Math.hypot(player.x-target.x,player.z-target.z)<(m.phase==='board'?1.5:3.2)&&player.y<1.5;$('prompt').hidden=!near;$('hack').hidden=!near;if(near){$('prompt').innerHTML='<kbd>E</kbd> HOLD TO '+label;$('hack').querySelector('span').textContent=label;if(held&&!m.requireRelease)m.progress=Math.min(1,m.progress+dt/duration);else m.progress=Math.max(0,m.progress-dt*.25);$('hack').querySelector('i').style.width=m.progress*100+'%';if(m.progress>=1){m.progress=0;if(m.phase==='core'){m.phase='call';stationWorld.coreMesh.visible=false;score+=1200;health=clamp(health+30,0,100);focus=100;toast('CORE SECURED. Insert it at CALL on platform 01.',5);tone(600,.5,.12,'sine',1200);}else if(m.phase==='call'){m.phase='defend';m.wait=35;spawnTimer=.5;spawnEnemy();spawnEnemy();toast('TRAIN REQUEST ACCEPTED. Survive for 35 seconds.',5);tone(180,.5,.1,'square',360);}else if(m.phase==='board'){m.phase='complete';finish(true);}}}else m.progress=0;
}

function makeGun(){const weapon=window.NULLVISUALS.viewWeapon(camera);gun=weapon.group;gunMuzzle=weapon.muzzle;weaponFlash=weapon.flash;flashLight=weapon.light;gun.position.set(.31,-.29,-.53);}
function makeAgent(x,z){if(window.NULLVISUALS?.agent){const visual=window.NULLVISUALS.agent(Math.floor(rand()*2));const group=visual.root;group.position.set(x,0,z);scene.add(group);const e={group,head:visual.head,torso:visual.body,realVisual:visual,hp:100,cooldown:range(.8,2.4),phase:rand()*TAU,dead:false,hit:0,death:0};group.traverse(o=>{if(o.isMesh)o.userData.enemy=e;});enemies.push(e);return e;}const group=new THREE.Group();group.position.set(x,0,z);const coat=enemyMat.coat||(enemyMat.coat=mat(0x19221e,.74,.12)),shirt=enemyMat.shirt||(enemyMat.shirt=mat(0xc0cabc,.92,.0)),skin=enemyMat.skin||(enemyMat.skin=mat(0xb5aa8d,.7,.02)),glasses=enemyMat.glasses||(enemyMat.glasses=mat(0x030806,.1,.85)),boot=enemyMat.boot||(enemyMat.boot=mat(0x0d1510,.4,.2));
const torso=box(.67,.86,.36,coat,0,1.3,0,group);box(.27,.55,.035,shirt,0,1.45,.201,group);box(.06,.45,.05,boot,0,1.4,.235,group);
const head=new THREE.Mesh(new THREE.SphereGeometry(.235,12,10),skin);head.scale.set(.88,1.17,.86);head.position.set(0,2.015,0);head.castShadow=true;group.add(head);
const hair=new THREE.Mesh(new THREE.SphereGeometry(.238,12,8,0,TAU,0,Math.PI*.42),coat);hair.position.set(0,2.05,0);group.add(hair);
box(.39,.075,.08,glasses,0,2.05,.18,group);box(.07,.13,.09,skin,0,1.97,.2,group);
const legs=[];for(const s of [-1,1]){const leg=new THREE.Group();leg.position.set(s*.18,.99,0);group.add(leg);box(.25,.72,.27,coat,0,-.35,0,leg);box(.27,.15,.43,boot,0,-.78,.06,leg);legs.push(leg);}
const arms=[];for(const s of [-1,1]){const arm=new THREE.Group();arm.position.set(s*.43,1.7,0);group.add(arm);box(.21,.58,.22,coat,0,-.27,0,arm);box(.19,.15,.18,skin,0,-.61,0,arm);arms.push(arm);}
const pistol=box(.1,.11,.36,glasses,0,-.61,.14,arms[1]);const glow=new THREE.Mesh(new THREE.SphereGeometry(.04,8,6),new THREE.MeshBasicMaterial({color:0xff554a}));glow.position.set(.025,2.055,.227);group.add(glow);
scene.add(group);const e={group,head,torso,legs,arms,hp:100,cooldown:range(.8,2.4),phase:rand()*TAU,dead:false,hit:0,death:0};group.traverse(o=>{if(o.isMesh)o.userData.enemy=e;});enemies.push(e);return e;}

// Sound is synthesized locally; no autoplay or remote audio downloads.
let audioContext,master,audioStarted=false,noiseBuffer;
function initAudio(){if(audioStarted){audioContext?.resume();return;}try{audioContext=new (window.AudioContext||window.webkitAudioContext)();master=audioContext.createGain();master.gain.value=soundOn?.55:0;master.connect(audioContext.destination);noiseBuffer=audioContext.createBuffer(1,audioContext.sampleRate*2,audioContext.sampleRate);const data=noiseBuffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=Math.random()*2-1;
const wind=audioContext.createBufferSource();wind.buffer=noiseBuffer;wind.loop=true;const filter=audioContext.createBiquadFilter();filter.type='lowpass';filter.frequency.value=500;const vol=audioContext.createGain();vol.gain.value=.035;wind.connect(filter).connect(vol).connect(master);wind.start();for(const freq of [43.65,65.4]){const o=audioContext.createOscillator(),g=audioContext.createGain();o.type='sine';o.frequency.value=freq;g.gain.value=.055;o.connect(g).connect(master);o.start();}audioStarted=true;}catch{}}
function tone(freq,length=.1,gain=.1,type='sine',end=freq){if(!audioContext||!soundOn)return;const o=audioContext.createOscillator(),g=audioContext.createGain(),t=audioContext.currentTime;o.type=type;o.frequency.setValueAtTime(freq,t);o.frequency.exponentialRampToValueAtTime(Math.max(10,end),t+length);g.gain.setValueAtTime(gain,t);g.gain.exponentialRampToValueAtTime(.001,t+length);o.connect(g).connect(master);o.start();o.stop(t+length);}
function gunSound(){if(!audioContext||!soundOn)return;const s=audioContext.createBufferSource(),f=audioContext.createBiquadFilter(),g=audioContext.createGain(),t=audioContext.currentTime;s.buffer=noiseBuffer;f.type='lowpass';f.frequency.value=2400;g.gain.setValueAtTime(.3,t);g.gain.exponentialRampToValueAtTime(.001,t+.13);s.connect(f).connect(g).connect(master);s.start();s.stop(t+.14);tone(140,.1,.22,'triangle',45);}
function toast(message,duration=3.3){$('toast').textContent=message;toastTimer=duration;$('toast').style.opacity='1';}
function spawnEnemy(){const points=currentLevel===2?stationWorld.spawnPoints:[[-26,31],[26,30],[-27,-33],[27,-34],[-28,1],[28,-9],[11,-36],[-14,35]];let chosen=points[Math.floor(rand()*points.length)];for(let i=0;i<12;i++){const p=points[Math.floor(rand()*points.length)];if(!circleBlocked(p[0],p[1],.42,0)&&Math.hypot(p[0]-player.x,p[1]-player.z)>18){chosen=p;break;}}const e=makeAgent(chosen[0],chosen[1]);burst(e.group.position.clone().add(v3(0,1,0)),0x9bff88,14);}
function clearDynamic(){for(const e of enemies){scene.remove(e.group);if(e.realVisual)window.NULLVISUALS.disposeAgent(e.realVisual);else e.group.traverse(o=>o.geometry?.dispose());}enemies.length=0;for(const arr of [bullets,particles,pickups]){for(const o of arr){scene.remove(o.mesh);if(o.line){scene.remove(o.line);o.line.geometry.dispose();}if(o.trace){o.mesh.geometry.dispose();o.mesh.material.dispose();}else if(arr===pickups)o.mesh.material.dispose();}arr.length=0;}}
function startGame(level=currentLevel){if(!renderer||level===2&&!levelTwoUnlocked)return;initAudio();clearDynamic();switchWorld(level);difficulty=$('difficulty').value;state='playing';elapsed=0;kills=0;score=0;health=100;focus=100;ammo=24;relaysDone=0;yaw=0;pitch=0;vy=0;jumps=0;shotTimer=0;reloadTimer=0;dashTimer=0;dashLeft=0;spawnTimer=4;slow=false;slowLatched=false;shooting=false;dragLook=false;timeScale=1;gunKick=0;damageFlash=0;hitFlash=0;killFlash=0;invincible=2;keys.clear();touch.x=touch.y=0;touch.slow=touch.hack=false;camera.fov=78;camera.updateProjectionMatrix();stationMission={phase:'breakers',wait:35,progress:0};if(currentLevel===2){stationWorld.reset();player.copy(stationWorld.start);}else{player.set(0,0,24);for(const r of relays){r.done=false;r.progress=0;r.beam.visible=true;r.light.intensity=12;r.ring.material.color.setHex(0xc4ff9d);}exitRing.material.opacity=0;}
document.body.classList.add('playing');$('menu').hidden=true;$('pause').hidden=true;$('end').hidden=true;$('briefing').hidden=true;$('hud').hidden=false;$('prompt').hidden=$('hack').hidden=true;$('touch-controls').hidden=!isTouch;$('hack').querySelector('span').textContent=currentLevel===1?'BREACHING RELAY':'RECOVER DATA CORE';$('relay-list').innerHTML=currentLevel===1?'<span>01 <i></i></span><span>02 <i></i></span><span>03 <i></i></span>':'<span>POWER <i></i></span><span>CORE <i></i></span><span>TRAIN <i></i></span>';$('mission-label').textContent=currentLevel===1?'01 / THE ROOFTOPS':'02 / LAST TRAIN';camera.position.copy(player).add(v3(0,1.72,0));camera.rotation.set(0,0,0);gun.visible=true;for(let i=0;i<(difficulty==='easy'?3:4);i++)spawnEnemy();toast(currentLevel===1?'Follow the green beacons. Hold SHIFT to bend time.':'Shoot power cells A and B. Then retrieve the archive core.',6);requestLock();lastTime=performance.now();updateHUD();}
function requestLock(){if(isTouch)return;try{const p=$('world').requestPointerLock();p?.catch(()=>toast('Click the arena to capture your mouse. You can also drag to look.',4));}catch{toast('Drag to look. Click the arena to capture your mouse.',4);}}
function pauseGame(){if(state!=='playing')return;state='paused';shooting=false;keys.clear();touch.x=touch.y=0;touch.slow=touch.hack=false;$('pause').hidden=false;$('touch-controls').hidden=true;document.exitPointerLock?.();}
function resumeGame(){if(state!=='paused')return;state='playing';$('pause').hidden=true;$('touch-controls').hidden=!isTouch;requestLock();lastTime=performance.now();}
function titleScreen(){state='menu';clearDynamic();keys.clear();shooting=false;slow=false;touch.x=touch.y=0;touch.slow=touch.hack=false;document.body.classList.remove('playing');$('menu').hidden=false;$('hud').hidden=true;$('pause').hidden=true;$('end').hidden=true;$('briefing').hidden=true;$('touch-controls').hidden=true;$('time-wash').style.opacity=0;document.exitPointerLock?.();updateCampaignMenu();selectMission();}
function finish(won){if(state!=='playing')return;state=won?'won':'lost';slow=false;shooting=false;keys.clear();touch.x=touch.y=0;touch.slow=touch.hack=false;document.exitPointerLock?.();$('end').hidden=false;$('hud').hidden=true;$('touch-controls').hidden=true;$('time-wash').style.opacity=0;const first=won&&currentLevel===1;$('end-eyebrow').textContent=first?'ROOFTOP CLEAR / MISSION 02 UNLOCKED':won?'CAMPAIGN COMPLETE':'CONNECTION TERMINATED';$('end-title').textContent=first?'The exit was a beginning.':won?'The signal is free.':'The system found you.';$('end-copy').textContent=first?'Your operator intercepted an archive beneath Mara Central. Take the last train into the next layer of the simulation.':won?'You stole the archive, survived the platform ambush and escaped aboard the last train. Both missions are complete.':currentLevel===2?'Retry Last Train. Destroy both power cells, recover the core, then use cover while the train arrives.':'Use cover, slow the bullets, and collect green shards to recover.';$('next-level').hidden=!first;$('again').className=first?'secondary':'primary';$('again').innerHTML=(first?'REPLAY THE ROOFTOPS':currentLevel===2?'RETRY LAST TRAIN':'ENTER AGAIN')+' <span>↗</span>';if(won){if(currentLevel===1){levelTwoUnlocked=true;safeStorage.set('nullshift-level2','unlocked');}else{stationMission.phase='complete';campaignComplete=true;safeStorage.set('nullshift-campaign','complete');}score+=Math.max(0,3000-Math.floor(elapsed)*5)+Math.round(health)*10;tone(523,.5,.15,'sine',1046);}else tone(90,.8,.2,'triangle',30);$('end-score').textContent=Math.round(score).toLocaleString();$('end-kills').textContent=kills;$('end-time').textContent=clockText(elapsed);const key=currentLevel===1?'nullshift-best':'nullshift-best-2';const best=Number(safeStorage.get(key)||0);if(score>best)safeStorage.set(key,String(Math.round(score)));updateRecord();updateCampaignMenu();}
function updateRecord(){const best=Number(safeStorage.get(currentLevel===1?'nullshift-best':'nullshift-best-2')||0);$('record').textContent=best?`MISSION ${currentLevel} BEST / ${best.toLocaleString()} POINTS`:'YOUR NEXT EXIT IS WAITING.';}
function reload(){if(state!=='playing'||reloadTimer>0||ammo===24)return;reloadTimer=1.3;tone(300,.07,.08,'square',160);}
function jump(){if(state==='playing'&&jumps<2){vy=jumps===0?8.5:8.3;jumps++;tone(jumps===2?340:200,.15,.035,'sine',100);}}
function dash(){if(state!=='playing'||dashTimer>0)return;dashTimer=2.1;dashLeft=.19;invincible=Math.max(invincible,.27);tone(190,.25,.1,'sawtooth',45);}
function burst(position,color,count=9){shared.sparkMaterials ||= new Map();if(!shared.sparkMaterials.has(color))shared.sparkMaterials.set(color,new THREE.MeshBasicMaterial({color}));const material=shared.sparkMaterials.get(color);for(let i=0;i<count;i++){const mesh=new THREE.Mesh(shared.sparkGeometry,material);mesh.position.copy(position);const velocity=v3(range(-4,4),range(1,6),range(-4,4));scene.add(mesh);particles.push({mesh,velocity,life:range(.25,.7),max:.7});}}
function trace(start,end,color=0xc8ffa7,lifetime=.07){const mesh=new THREE.Line(new THREE.BufferGeometry().setFromPoints([start,end]),new THREE.LineBasicMaterial({color,transparent:true,opacity:.7}));scene.add(mesh);particles.push({mesh,velocity:v3(),life:lifetime,max:lifetime,trace:true});}
function shoot(){if(state!=='playing'||shotTimer>0||reloadTimer>0)return;if(ammo<=0){reload();return;}ammo--;shotTimer=.135;gunKick=.065;pitch=clamp(pitch+.006,-1.35,1.35);weaponFlash.visible=true;flashLight.intensity=5;gunSound();camera.updateMatrixWorld();raycaster.setFromCamera(new THREE.Vector2(0,0),camera);let max=obstacleDistance(raycaster.ray.origin,raycaster.ray.direction,100);let target=null;let headshot=false;
const meshes=[];for(const e of enemies)if(!e.dead)e.group.traverse(m=>{if(m.isMesh&&(!e.realVisual||m.userData.hitbox))meshes.push(m);});scene.updateMatrixWorld(true);if(currentLevel===2&&stationMission.phase==='breakers')for(const cell of stationWorld.breakers)if(!cell.done){cell.orb.userData.powerCell=cell;meshes.push(cell.orb);}const hits=raycaster.intersectObjects(meshes,false);if(hits.length&&hits[0].distance<max){const h=hits[0];if(h.object.userData.powerCell){max=h.distance;damagePowerCell(h.object.userData.powerCell);}else{target=h.object.userData.enemy;headshot=h.object===target.head||h.point.y-target.group.position.y>1.83;max=h.distance;target.hp-=headshot?110:40;target.hit=.1;burst(h.point,0xc1ffa1,headshot?9:5);hitFlash=.15;if(target.hp<=0)killAgent(target,headshot);else tone(520,.045,.035,'sine');}}
const end=raycaster.ray.origin.clone().addScaledVector(raycaster.ray.direction,max);const muzzle=gunMuzzle.getWorldPosition(v3());trace(muzzle,end);if(!target&&max<100)burst(end,0xe8daab,4);if(ammo===0)reload();}
function killAgent(e,headshot){if(e.dead)return;e.dead=true;e.death=.8;kills++;const gained=headshot?200:100;score+=gained;focus=clamp(focus+7,0,100);killFlash=1.3;$('kill-notice').textContent=`${headshot?'HEADSHOT':'AGENT REMOVED'}  +${gained}`;tone(headshot?1000:750,.1,.08,'sine',600);const mesh=new THREE.Mesh(shared.pickupGeometry,new THREE.MeshStandardMaterial({color:0xa8ff7c,emissive:0x77ff50,emissiveIntensity:1.5,roughness:.2,metalness:.6}));mesh.position.copy(e.group.position).add(v3(0,.55,0));scene.add(mesh);pickups.push({mesh,life:25});}
function enemyShoot(e){if(e.realVisual)e.realVisual.recoil=1;const origin=e.realVisual?e.realVisual.gun.getWorldPosition(v3()).add(v3(0,0,.24).applyQuaternion(e.group.quaternion)):e.group.position.clone().add(v3(.3,1.42,0));const target=player.clone().add(v3(range(-.7,.7),1.05+range(-.25,.35),range(-.7,.7)));const dir=target.sub(origin).normalize();if(obstacleDistance(origin,dir,origin.distanceTo(player))<origin.distanceTo(player)-1)return;
const mesh=new THREE.Mesh(shared.bulletGeometry,shared.bulletMaterial);mesh.position.copy(origin);const speed=difficulty==='easy'?17:difficulty==='hard'?26:21;const line=new THREE.Line(new THREE.BufferGeometry().setFromPoints([origin,origin.clone().addScaledVector(dir,-1.7)]),shared.trailMaterial);scene.add(mesh,line);bullets.push({mesh,line,velocity:dir.multiplyScalar(speed),life:5});tone(95,.07,.025,'triangle',50);}
function damage(amount){if(invincible>0)return;health=Math.max(0,health-amount);damageFlash=.75;invincible=.22;tone(60,.15,.13,'triangle',30);if(health<=0)finish(false);}
function simulate(dt){if(state!=='playing')return;elapsed+=dt;const slowWanted=keys.has('ShiftLeft')||keys.has('ShiftRight')||touch.slow;if(!slowWanted)slowLatched=false;const nextSlow=slowWanted&&focus>1&&!slowLatched;if(nextSlow&&!slow)tone(180,.6,.13,'sine',45);slow=nextSlow;if(slow){focus=Math.max(0,focus-dt*15);if(focus<=1)slowLatched=true;}else focus=clamp(focus+dt*9,0,100);timeScale=slow?.18:1;const worldDt=dt*timeScale;
shotTimer=Math.max(0,shotTimer-dt);dashTimer=Math.max(0,dashTimer-dt);invincible=Math.max(0,invincible-dt);if(reloadTimer>0){reloadTimer=Math.max(0,reloadTimer-dt);if(!reloadTimer){ammo=24;tone(700,.06,.055,'square',300);}}if(shooting)shoot();
let mx=(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0)+touch.x,mz=(keys.has('KeyW')?1:0)-(keys.has('KeyS')?1:0)-touch.y;const n=Math.hypot(mx,mz);if(n>1){mx/=n;mz/=n;}let speed=8.6;if(dashLeft>0){dashLeft-=dt;speed=36;if(n<.1)mz=1;}const dx=(Math.cos(yaw)*mx-Math.sin(yaw)*mz)*speed*dt,dz=(-Math.sin(yaw)*mx-Math.cos(yaw)*mz)*speed*dt;moveBody(player,dx,dz,.38,player.y);const oldY=player.y;vy-=22*dt;player.y+=vy*dt;let ground=0;for(const b of colliders){if(player.x>b.x-b.w-.25&&player.x<b.x+b.w+.25&&player.z>b.z-b.d-.25&&player.z<b.z+b.d+.25&&oldY>=b.height-.15)ground=Math.max(ground,b.height);}if(player.y<=ground){player.y=ground;vy=0;jumps=0;}
gunBob+=dt*(n>.1?11:2);const bob=(n>.1?.032:.009)*Math.sin(gunBob);camera.position.set(player.x,player.y+1.72+bob,player.z);camera.rotation.set(pitch,yaw,slow?Math.sin(realTime*1.1)*.004:0,'YXZ');const wantedFov=slow?83:dashLeft>0?91:78;camera.fov+=(wantedFov-camera.fov)*Math.min(1,dt*7);camera.updateProjectionMatrix();gunKick*=Math.pow(.001,dt);gun.position.set(.31+Math.sin(gunBob*.5)*.008,-.29+bob*.35-(reloadTimer>0?Math.sin((1.3-reloadTimer)/1.3*Math.PI)*.3:0),-.53+gunKick);gun.rotation.set(gunKick*1.3,0,reloadTimer>0?-.35*Math.sin(reloadTimer/1.3*Math.PI):-.015);weaponFlash.visible=shotTimer>.095;flashLight.intensity=weaponFlash.visible?4:0;
spawnTimer-=worldDt;const living=enemies.filter(e=>!e.dead).length;const intensity=currentLevel===1?relaysDone:stationMission.phase==='defend'?2:0;const cap=(difficulty==='easy'?5:difficulty==='hard'?10:7)+intensity;if(spawnTimer<=0&&living<cap){spawnEnemy();spawnTimer=Math.max(2.2,6-intensity*.9);}
for(let i=enemies.length-1;i>=0;i--){const e=enemies[i];if(e.dead){e.death-=worldDt;e.group.rotation.z+=(e.group.position.x<player.x?1:-1)*worldDt*1.7;e.group.position.y-=worldDt*.6;if(e.death<=0){burst(e.group.position.clone().add(v3(0,1,0)),0x8eea81,9);scene.remove(e.group);if(e.realVisual)window.NULLVISUALS.disposeAgent(e.realVisual);else e.group.traverse(o=>o.geometry?.dispose());enemies.splice(i,1);}continue;}
const p=e.group.position,dist=Math.hypot(player.x-p.x,player.z-p.z);const dirX=(player.x-p.x)/Math.max(.1,dist),dirZ=(player.z-p.z)/Math.max(.1,dist);e.group.rotation.y=Math.atan2(dirX,dirZ);e.phase+=worldDt*6.8;e.cooldown-=worldDt;e.hit=Math.max(0,e.hit-dt);e.group.position.y=e.hit>0?.06:0;
const chase=dist>12?1:dist<6?-.55:.12;const strafe=Math.sin(realTime*.8+e.phase*.05+e.group.id)*.5;const walkSpeed=(difficulty==='hard'?3.2:2.4)*worldDt;const ex=(dirX*chase+dirZ*strafe)*walkSpeed,ez=(dirZ*chase-dirX*strafe)*walkSpeed;const beforeX=p.x,beforeZ=p.z;moveBody(p,ex,ez,.42,0);if(Math.abs(p.x-beforeX)+Math.abs(p.z-beforeZ)<.006&&dist>10){const side=(e.group.id%2)*2-1;moveBody(p,dirZ*side*walkSpeed,-dirX*side*walkSpeed,.42,0);}
if(e.realVisual){window.NULLVISUALS.animateAgent(e.realVisual,worldDt,Math.abs(p.x-beforeX)+Math.abs(p.z-beforeZ)>.002);}else{e.legs.forEach((l,j)=>l.rotation.x=Math.sin(e.phase+j*Math.PI)*.42);e.arms[0].rotation.x=Math.sin(e.phase+Math.PI)*.16;e.arms[1].rotation.x=-1.3;}
if(e.cooldown<=0&&dist<43){enemyShoot(e);e.cooldown=range(difficulty==='hard'?.8:1.3,difficulty==='easy'?3.2:2.3);}if(dist<1.7&&player.y<1.25&&e.cooldown<.6&&obstacleDistance(p.clone().add(v3(0,1.2,0)),v3(dirX,0,dirZ),dist)>=dist-.05){damage(difficulty==='hard'?16:10);e.cooldown=1.8;}}
for(let i=bullets.length-1;i>=0;i--){const b=bullets[i],old=b.mesh.position.clone(),travel=b.velocity.length()*worldDt,dir=b.velocity.clone().normalize();b.mesh.position.addScaledVector(b.velocity,worldDt);b.life-=worldDt;const coverDistance=obstacleDistance(old,dir,travel);const playerDistance=intersectBox(old,dir,{x:player.x,z:player.z,w:.42,d:.42,bottom:player.y+.1,height:player.y+1.9},travel);const collided=coverDistance<travel;if(playerDistance!==false&&playerDistance<=coverDistance){damage(difficulty==='easy'?7:difficulty==='hard'?15:10);b.life=0;}else if(collided){b.mesh.position.copy(old).addScaledVector(dir,coverDistance);burst(b.mesh.position,0xffbb77,3);b.life=0;}const p=b.line.geometry.attributes.position;p.setXYZ(0,b.mesh.position.x,b.mesh.position.y,b.mesh.position.z);const tail=b.mesh.position.clone().addScaledVector(dir,slow?-2.8:-1.5);p.setXYZ(1,tail.x,tail.y,tail.z);p.needsUpdate=true;if(b.life<=0||b.mesh.position.y<0||Math.abs(b.mesh.position.x)>55||Math.abs(b.mesh.position.z)>55){scene.remove(b.mesh,b.line);b.line.geometry.dispose();bullets.splice(i,1);}}
for(let i=pickups.length-1;i>=0;i--){const p=pickups[i];p.life-=dt;p.mesh.rotation.y+=dt*1.7;p.mesh.position.y=.65+Math.sin(realTime*3+i)*.15;const d=Math.hypot(p.mesh.position.x-player.x,p.mesh.position.z-player.z);if(d<4&&player.y<2){p.mesh.position.x+=(player.x-p.mesh.position.x)*dt*5;p.mesh.position.z+=(player.z-p.mesh.position.z)*dt*5;}if(d<1.2&&player.y<2){health=clamp(health+16,0,100);focus=clamp(focus+22,0,100);score+=25;p.life=0;tone(800,.18,.07,'sine',1300);toast('SHARD RECOVERED  /  +16 integrity  +22 focus',1.5);}if(p.life<=0){scene.remove(p.mesh);p.mesh.material.dispose();pickups.splice(i,1);}}
if(state!=='playing')return;if(currentLevel===2){updateStationMission(dt);return;}
let near=null;for(const r of relays){if(!r.done&&Math.hypot(player.x-r.x,player.z-r.z)<3.2&&player.y<1.5)near=r;r.ring.rotation.z+=worldDt*.3;}
$('prompt').hidden=!near;$('hack').hidden=!near;if(near){$('prompt').innerHTML='<kbd>E</kbd> HOLD TO HACK RELAY';if(keys.has('KeyE')||touch.hack){near.progress+=dt/2.5;if(near.progress>=1){near.done=true;near.progress=1;relaysDone++;score+=750;health=clamp(health+25,0,100);focus=100;near.beam.visible=false;near.light.intensity=3;near.ring.material.color.setHex(0x47785b);burst(near.group.position.clone().add(v3(0,2,0)),0xbaff91,22);tone(660,.4,.12,'sine',1320);toast(relaysDone===3?'EXIT UNLOCKED. Reach the phone to unlock mission 02.':`RELAY ${relaysDone}/3 BREACHED  /  Integrity restored`,4);spawnEnemy();spawnEnemy();}}else near.progress=Math.max(0,near.progress-dt*.18);$('hack').querySelector('i').style.width=near.progress*100+'%';}
if(relaysDone===3){exitRing.material.opacity=.34+Math.sin(realTime*3)*.13;if(player.distanceTo(exitPos)<2.1)finish(true);}
}
function updateEffects(dt,worldDt){if(currentLevel===1)window.NULLVISUALS?.update(worldDt,slow,relaysDone===3,detailedPhone);else stationWorld?.animate(worldDt,stationMission.phase,stationMission.wait,slow);damageFlash=Math.max(0,damageFlash-dt*2);hitFlash=Math.max(0,hitFlash-dt);killFlash=Math.max(0,killFlash-dt);$('damage').style.opacity=damageFlash;$('hitmarker').style.opacity=hitFlash>0?1:0;$('kill-notice').style.opacity=Math.min(1,killFlash*3);$('time-wash').style.opacity=slow&&state==='playing'?1:0;$('bullet-label').style.opacity=slow&&state==='playing'?1:0;if(toastTimer>0){toastTimer-=dt;if(toastTimer<=0)$('toast').style.opacity=0;}
for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.life-=worldDt;if(!p.trace){p.velocity.y-=12*worldDt;p.mesh.position.addScaledVector(p.velocity,worldDt);p.mesh.scale.setScalar(Math.max(.05,p.life/p.max));}if(p.life<=0){scene.remove(p.mesh);if(p.trace){p.mesh.geometry.dispose();p.mesh.material.dispose();}particles.splice(i,1);}}
if(currentLevel!==1||!rain)return;const pos=rain.geometry.attributes.position;for(let i=0;i<pos.count;i+=2){let y=pos.getY(i)-worldDt*20;if(y<-.5)y=36;pos.setY(i,y);pos.setY(i+1,y-.85); }pos.needsUpdate=true;}
function updateHUD(){if(state!=='playing'&&state!=='paused')return;$('health-number').textContent=Math.ceil(health);$('health-bar').style.width=health+'%';$('health-bar').style.background=health<30?'#ff867e':'#d4f2cd';$('focus-number').textContent=Math.ceil(focus)+'%';$('focus-bar').style.width=focus+'%';$('ammo').textContent=String(ammo).padStart(2,'0');$('reload-label').innerHTML=reloadTimer>0?'RELOADING…':'<kbd>R</kbd> RELOAD';$('clock').textContent=clockText(elapsed);$('kills').textContent=`${kills} ELIMINATED`;$('objective').textContent=currentLevel===2?stationObjective()[0]:relaysDone<3?'Break the three relays':'Reach the exit';$('objective-sub').textContent=currentLevel===2?stationObjective()[1]:relaysDone<3?'Find the green beacons. Hold E to hack.':'All relays breached. Follow the EXIT beacon.';[...$('relay-list').children].forEach((el,i)=>el.classList.toggle('done',currentLevel===1?!!relays[i]?.done:i===0?stationMission.phase!=='breakers':i===1?['call','defend','board','complete'].includes(stationMission.phase):['board','complete'].includes(stationMission.phase)));drawRadar();}
function drawRadar(){const ctx=$('minimap').getContext('2d');ctx.clearRect(0,0,200,200);ctx.strokeStyle='#9acc9925';ctx.lineWidth=1;for(let p=20;p<200;p+=40){ctx.beginPath();ctx.moveTo(p,0);ctx.lineTo(p,200);ctx.moveTo(0,p);ctx.lineTo(200,p);ctx.stroke();}const fx=x=>100+x*2.2,fz=z=>100+z*2.2;ctx.strokeStyle='#aecdad55';ctx.strokeRect(fx(-31),fz(-39),136.4,171.6);ctx.fillStyle='#71887870';for(const b of colliders)ctx.fillRect(fx(b.x-b.w),fz(b.z-b.d),b.w*4.4,b.d*4.4);if(currentLevel===2){for(const b of stationWorld.breakers){ctx.fillStyle=b.done?'#42664b':'#baff8d';ctx.fillRect(fx(b.x)-3,fz(b.z)-3,6,6);}const target=stationMission.phase==='core'?stationWorld.core.position:stationMission.phase==='board'?exitPos:stationWorld.console.position;ctx.strokeStyle='#caffb6';ctx.strokeRect(fx(target.x)-5,fz(target.z)-5,10,10);}
for(const r of relays){ctx.fillStyle=r.done?'#42664b':'#baff8d';ctx.fillRect(fx(r.x)-3,fz(r.z)-3,6,6);}if(currentLevel===1&&relaysDone===3){ctx.strokeStyle='#d2fff0';ctx.strokeRect(fx(exitPos.x)-5,fz(exitPos.z)-5,10,10);}ctx.fillStyle='#ff8f7f';for(const e of enemies)if(!e.dead){ctx.beginPath();ctx.arc(fx(e.group.position.x),fz(e.group.position.z),2.4,0,TAU);ctx.fill();}ctx.save();ctx.translate(fx(player.x),fz(player.z));ctx.rotate(-yaw);ctx.fillStyle='#f4ffe9';ctx.beginPath();ctx.moveTo(0,-6);ctx.lineTo(-4,4);ctx.lineTo(0,2);ctx.lineTo(4,4);ctx.closePath();ctx.fill();ctx.restore();}
function updateMarkers(){if(state!=='playing')return;camera.updateMatrixWorld();frustumDirection.set(0,0,-1).applyQuaternion(camera.quaternion);const w=innerWidth,h=innerHeight;function place(el,p,label,distance){const front=p.clone().sub(camera.position).dot(frustumDirection)>0;const v=p.clone().project(camera);el.hidden=!front||Math.abs(v.x)>1.05||Math.abs(v.y)>1.05;if(!el.hidden){el.style.left=(v.x*.5+.5)*w+'px';el.style.top=(-v.y*.5+.5)*h+'px';el.innerHTML=`<strong>${label}</strong>${Math.round(distance)} M`;}}
if(currentLevel===2){for(const m of stationWorld.markers){const show=m.kind==='cell'?stationMission.phase==='breakers'&&!m.cell.done:m.kind==='core'?stationMission.phase==='core':m.kind==='call'?['call','defend'].includes(stationMission.phase):stationMission.phase==='board';if(show)place(m.element,m.position,m.kind==='call'&&stationMission.phase==='defend'?Math.ceil(stationMission.wait)+'s':m.label,player.distanceTo(m.position));else m.element.hidden=true;}return;}
for(const [i,r] of relays.entries()){if(r.done){r.marker.hidden=true;continue;}place(r.marker,v3(r.x,4.6,r.z),`0${i+1}`,Math.hypot(player.x-r.x,player.z-r.z));}for(const m of markers){if(relaysDone<3)m.element.hidden=true;else place(m.element,m.position,'EXIT',player.distanceTo(exitPos));}}
function makePost(){renderTarget=new THREE.WebGLRenderTarget(innerWidth,innerHeight,{type:THREE.HalfFloatType});renderTarget.samples=quality==='high'?2:0;screenScene=new THREE.Scene();screenCamera=new THREE.OrthographicCamera(-1,1,1,-1,0,1);postMaterial=new THREE.ShaderMaterial({uniforms:{image:{value:renderTarget.texture},resolution:{value:new THREE.Vector2(innerWidth,innerHeight)},time:{value:0},slow:{value:0}},vertexShader:'varying vec2 uv0; void main(){uv0=uv;gl_Position=vec4(position.xy,0.,1.);}',fragmentShader:`uniform sampler2D image;uniform vec2 resolution;uniform float time;uniform float slow;varying vec2 uv0;
void main(){vec2 uv=uv0;vec2 aberration=(uv-.5)*.0016*slow;vec3 c=texture2D(image,uv).rgb;c.r=texture2D(image,uv+aberration).r;c.b=texture2D(image,uv-aberration).b;vec3 bloom=vec3(0.);for(int i=0;i<8;i++){float a=float(i)*.785398;vec2 off=vec2(cos(a),sin(a))*4./resolution;vec3 s=texture2D(image,uv+off).rgb;bloom+=max(s-.67,0.);vec3 s2=texture2D(image,uv+off*3.).rgb;bloom+=max(s2-.72,0.)*.5;}c+=bloom*.085;c*=vec3(.94,1.015,.965);float grain=fract(sin(dot(uv*resolution+fract(time),vec2(12.9898,78.233)))*43758.5453);c+=(grain-.5)*.012;gl_FragColor=vec4(c,1.);
#include <tonemapping_fragment>
#include <colorspace_fragment>
}`});screenScene.add(new THREE.Mesh(new THREE.PlaneGeometry(2,2),postMaterial));}
function render(){const high=visualQuality==='high';if(high&&(stepCount%3===0||state==='menu')){const size=renderer.getDrawingBufferSize(new THREE.Vector2());if(reflectionTarget.width!==Math.round(size.x*.45))reflectionTarget.setSize(Math.round(size.x*.45),Math.round(size.y*.45));mirrorCamera.copy(camera,false);mirrorCamera.position.y=-camera.position.y;const direction=camera.getWorldDirection(v3());const target=camera.position.clone().add(direction);target.y=-target.y;mirrorCamera.up.set(0,-1,0);mirrorCamera.lookAt(target);mirrorCamera.updateMatrixWorld();mirrorCamera.updateProjectionMatrix();mirrorMatrix.set(.5,0,0,.5,0,.5,0,.5,0,0,.5,.5,0,0,0,1);mirrorMatrix.multiply(mirrorCamera.projectionMatrix).multiply(mirrorCamera.matrixWorldInverse);floor.visible=false;gun.visible=false;rain.visible=false;renderer.setRenderTarget(reflectionTarget);renderer.render(scene,mirrorCamera);floor.visible=true;gun.visible=state!=='menu';rain.visible=currentLevel===1;}
postMaterial.uniforms.time.value=realTime;postMaterial.uniforms.slow.value=slow?1:0;renderer.setRenderTarget(renderTarget);renderer.render(scene,camera);renderer.setRenderTarget(null);renderer.render(screenScene,screenCamera);}
function loop(now){requestAnimationFrame(loop);const dt=Math.min(.05,Math.max(0,(now-lastTime)/1000));lastTime=now;realTime+=dt;stepCount++;if(!renderer)return;if(state==='playing'){simulate(dt);updateEffects(dt,dt*timeScale);hudClock+=dt;if(hudClock>.07){updateHUD();hudClock=0;}updateMarkers();}else if(state==='menu'){if(currentLevel===1){camera.position.set(19+Math.sin(realTime*.045)*4,10.5,33);camera.lookAt(-2,5,-15);}else{camera.position.set(-17+Math.sin(realTime*.06)*2,3.5,33);camera.lookAt(-1,3,-16);}gun.visible=false;updateEffects(dt,dt*.4);}else updateEffects(dt,0);render();}
function resize(){if(!renderer)return;const ratio=Math.min(devicePixelRatio||1,visualQuality==='high'?1.5:1);renderer.setPixelRatio(ratio);renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderTarget.setSize(Math.round(innerWidth*ratio),Math.round(innerHeight*ratio));postMaterial.uniforms.resolution.value.set(innerWidth*ratio,innerHeight*ratio);}
function setQuality(){quality=quality==='high'?'performance':'high';visualQuality=quality;safeStorage.set('nullshift-quality',quality);$('quality').textContent=`VISUALS: ${quality==='high'?'HIGH':'PERFORMANCE'}`;renderer.shadowMap.enabled=quality==='high';rain.geometry.setDrawRange(0,quality==='high'?2600:1100);resize();}
function setupInputs(){
$('mission-select').addEventListener('change',selectMission);$('next-level').addEventListener('click',nextLevel);$('briefing-start').addEventListener('click',()=>{$('mission-select').value='2';startGame(2);});$('briefing-menu').addEventListener('click',titleScreen);$('start').addEventListener('click',()=>startGame(Number($('mission-select').value)));$('resume').addEventListener('click',resumeGame);$('restart').addEventListener('click',()=>startGame(currentLevel));$('again').addEventListener('click',()=>startGame(currentLevel));$('quit').addEventListener('click',titleScreen);$('end-menu').addEventListener('click',titleScreen);$('pause-button').addEventListener('click',pauseGame);$('brand').addEventListener('click',e=>{e.preventDefault();if(state==='playing')pauseGame();});$('quality').addEventListener('click',setQuality);$('sound').addEventListener('click',()=>{soundOn=!soundOn;safeStorage.set('nullshift-sound',soundOn?'on':'off');$('sound').textContent=soundOn?'SOUND ON':'SOUND OFF';if(master)master.gain.setTargetAtTime(soundOn?.55:0,audioContext.currentTime,.1);});$('fullscreen').addEventListener('click',()=>{if(document.fullscreenElement)document.exitFullscreen?.();else $('game').requestFullscreen?.().catch(()=>toast('Use Chrome fullscreen from the browser menu.'));});$('controls-open').addEventListener('click',()=>$('controls').showModal());$('controls-close').addEventListener('click',()=>$('controls').close());$('controls-ready').addEventListener('click',()=>$('controls').close());
window.addEventListener('keydown',e=>{if(['Space','KeyW','KeyA','KeyS','KeyD','ShiftLeft','ShiftRight','KeyQ','KeyE','KeyR','ArrowUp','ArrowDown'].includes(e.code)&&state==='playing')e.preventDefault();if(e.code==='KeyP'||e.code==='Escape'){if(state==='playing')pauseGame();else if(state==='paused'&&e.code==='KeyP')resumeGame();return;}if(state!=='playing')return;keys.add(e.code);if(!e.repeat){if(e.code==='Space')jump();if(e.code==='KeyR')reload();if(e.code==='KeyQ')dash();}});
window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',pauseGame);document.addEventListener('visibilitychange',()=>{if(document.hidden)pauseGame();});document.addEventListener('pointerlockchange',()=>{if(!document.pointerLockElement&&state==='playing'&&!isTouch)pauseGame();});
$('world').addEventListener('mousedown',e=>{if(state!=='playing')return;if(e.button===0){shooting=true;dragLook=true;if(!document.pointerLockElement)requestLock();}});window.addEventListener('mouseup',()=>{shooting=false;dragLook=false;});window.addEventListener('mousemove',e=>{if(state!=='playing'||(!document.pointerLockElement&&!dragLook))return;yaw-=e.movementX*.0021;pitch=clamp(pitch-e.movementY*.0021,-1.35,1.35);});$('world').addEventListener('contextmenu',e=>e.preventDefault());window.addEventListener('resize',resize);
if(isTouch){let stickId=null,lookId=null,lastX=0,lastY=0;const stick=$('stick');stick.addEventListener('pointerdown',e=>{stickId=e.pointerId;stick.setPointerCapture(e.pointerId);});stick.addEventListener('pointermove',e=>{if(e.pointerId!==stickId)return;const b=stick.getBoundingClientRect();touch.x=clamp((e.clientX-b.x-55)/38,-1,1);touch.y=clamp((e.clientY-b.y-55)/38,-1,1);stick.firstElementChild.style.transform=`translate(${touch.x*30}px,${touch.y*30}px)`;});const stopStick=()=>{stickId=null;touch.x=touch.y=0;stick.firstElementChild.style.transform='';};stick.addEventListener('pointerup',stopStick);stick.addEventListener('pointercancel',stopStick);const look=$('touch-look');look.addEventListener('pointerdown',e=>{lookId=e.pointerId;lastX=e.clientX;lastY=e.clientY;look.setPointerCapture(e.pointerId);});look.addEventListener('pointermove',e=>{if(e.pointerId!==lookId)return;yaw-=(e.clientX-lastX)*.005;pitch=clamp(pitch-(e.clientY-lastY)*.005,-1.35,1.35);lastX=e.clientX;lastY=e.clientY;});look.addEventListener('pointerup',()=>lookId=null);look.addEventListener('pointercancel',()=>lookId=null);document.querySelectorAll('[data-touch]').forEach(b=>{const k=b.dataset.touch;b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);if(k==='shoot')shooting=true;if(k==='slow')touch.slow=true;if(k==='hack')touch.hack=true;if(k==='jump')jump();});const off=()=>{if(k==='shoot')shooting=false;if(k==='slow')touch.slow=false;if(k==='hack')touch.hack=false;};b.addEventListener('pointerup',off);b.addEventListener('pointercancel',off);});}
}
function snapshot(){return {status:state,mission:currentLevel,missionName:currentLevel===1?'The Rooftops':'Last Train',levelTwoUnlocked,campaignComplete,objective:currentLevel===2?stationObjective()[0]:relaysDone===3?'Reach the exit':'Break the three relays',station:currentLevel===2?{phase:stationMission.phase,trainSeconds:Math.ceil(stationMission.wait),powerCells:stationWorld.breakers.map(b=>({id:b.id,disabled:b.done,health:b.hp})),coreRecovered:['call','defend','board','complete'].includes(stationMission.phase)}:null,difficulty,health:Math.round(health),focus:Math.round(focus),ammo,reloading:reloadTimer>0,bulletTime:slow,relays:relays.map((r,i)=>({id:i+1,hacked:r.done,progress:Math.round(r.progress*100),x:r.x,z:r.z})),kills,score,seconds:Math.round(elapsed),livingAgents:enemies.filter(e=>!e.dead).length,enemyBullets:bullets.length,player:{x:+player.x.toFixed(2),y:+player.y.toFixed(2),z:+player.z.toFixed(2)},exitUnlocked:currentLevel===1?relaysDone===3:['board','complete'].includes(stationMission.phase),quality,sound:soundOn,visualPack:window.NULLVISUALS?.info()||null};}
function registerTools(){const context=document.modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const tool={name:'read_simulation_status',title:'Read simulation status',description:'Read the current NULL SHIFT mission, player vitals, relay progress and enemies. Does not alter the game.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(input){if(input===null||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('Expected an empty object.');return snapshot();}};try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
async function init(){try{if(!window.THREE)throw new Error('The graphics library is missing. Keep the assets folder next to index.html.');renderer=new THREE.WebGLRenderer({canvas:$('world'),antialias:true,powerPreference:'high-performance'});renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.35;renderer.shadowMap.enabled=quality==='high';renderer.shadowMap.type=THREE.PCFSoftShadowMap;scene=new THREE.Scene();scene.background=new THREE.Color(0x18302b);scene.fog=new THREE.FogExp2(0x203c32,.0065);camera=new THREE.PerspectiveCamera(78,innerWidth/innerHeight,.08,480);scene.add(camera);player=v3();raycaster=new THREE.Raycaster();frustumDirection=v3();shared.sparkGeometry=new THREE.BoxGeometry(.055,.055,.13);shared.pickupGeometry=new THREE.OctahedronGeometry(.27);shared.bulletGeometry=new THREE.SphereGeometry(.065,6,5);shared.bulletMaterial=new THREE.MeshBasicMaterial({color:0xffae78});shared.trailMaterial=new THREE.LineBasicMaterial({color:0xffcc8f,transparent:true,opacity:.9});hemi=new THREE.HemisphereLight(0xa5d6bd,0x162c1c,2.4);scene.add(hemi);shadowLight=new THREE.DirectionalLight(0xc5e6d3,2.2);shadowLight.position.set(-24,45,-35);shadowLight.castShadow=true;shadowLight.shadow.mapSize.set(1024,1024);Object.assign(shadowLight.shadow.camera,{left:-45,right:45,top:48,bottom:-48,near:1,far:110});shadowLight.shadow.bias=-.0008;shadowLight.shadow.normalBias=.045;scene.add(shadowLight);await window.NULLVISUALS.prepare();makeEnvironment();buildWorlds();makeGun();makePost();setupInputs();resize();$('quality').textContent=`VISUALS: ${quality==='high'?'HIGH':'PERFORMANCE'}`;$('sound').textContent=soundOn?'SOUND ON':'SOUND OFF';updateRecord();updateCampaignMenu();$('start').disabled=false;$('start').firstElementChild.textContent='ENTER THE SIMULATION';const art=new Image();art.onload=()=>{$('menu').querySelector('.menu-art').style.backgroundImage='url(assets/rooftop.png)';$('menu').querySelector('.menu-art').classList.add('ready');};art.src='assets/rooftop.png';window.NULLSHIFT=Object.freeze({getState:snapshot});registerTools();requestAnimationFrame(loop);
$('world').addEventListener('webglcontextlost',e=>{e.preventDefault();pauseGame();$('error').hidden=false;$('error-message').textContent='Chrome lost the graphics context. Close other graphics-heavy tabs and reload the game.';});
}catch(error){$('error').hidden=false;$('error-message').textContent=error.message.includes('WebGL')?'Enable graphics acceleration in Chrome settings, then reload. This game needs WebGL.':error.message;console.error(error);}}
init();
})();

